package Vista;

import java.util.*;

/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * @author mono-
 */
public class Precio extends JFrame {

    /**
     * Default constructor
     */
    public Precio() {
    }

    /**
     * 
     */
    private JLabel jLabel1;

    /**
     * 
     */
    private JTextField jTextField1;

    /**
     * Creates new form pRECIO
     */
    public void Precio() {
        // TODO implement here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return
     */
    private void initComponents() {
        // TODO implement here
        return null;
    }

    /**
     * @param evt 
     * @return
     */
    private void jTextField1ActionPerformed(ActionEvent evt) {
        // TODO implement here
        return null;
    }

    /**
     * @param args 
     * @return
     */
    public static void main(String args) {
        // TODO implement here
        return null;
    }

}