package Vista;

import java.util.*;

/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * @author mono-
 */
public class Salida extends JFrame {

    /**
     * Default constructor
     */
    public Salida() {
    }

    /**
     * 
     */
    private JButton btnButton;

    /**
     * 
     */
    private JComboBox cmbEnfermedad;

    /**
     * 
     */
    private JLabel jLabel1;

    /**
     * 
     */
    private JPanel jPanel1;

    /**
     * 
     */
    private JPanel jPanel2;

    /**
     * 
     */
    private JTextField jTextField1;

    /**
     * 
     */
    private JLabel lblLabel;

    /**
     * 
     */
    private JLabel lblLabel1;

    /**
     * 
     */
    private JLabel lblLabel2;

    /**
     * 
     */
    private JLabel lblLabel3;

    /**
     * 
     */
    private JLabel lblLabel4;

    /**
     * 
     */
    private JLabel lblLabel5;

    /**
     * 
     */
    private JTextField txtText1;

    /**
     * 
     */
    private JTextField txtText2;

    /**
     * 
     */
    private JTextField txtText3;

    /**
     * Creates new form Ventana
     */
    public void Salida() {
        // TODO implement here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return
     */
    private void initComponents() {
        // TODO implement here
        return null;
    }

    /**
     * @param evt 
     * @return
     */
    private void btnButtonActionPerformed(ActionEvent evt) {
        // TODO implement here
        return null;
    }

    /**
     * @param evt 
     * @return
     */
    private void txtText1ActionPerformed(ActionEvent evt) {
        // TODO implement here
        return null;
    }

    /**
     * @param evt 
     * @return
     */
    private void jTextField1ActionPerformed(ActionEvent evt) {
        // TODO implement here
        return null;
    }

    /**
     * @param args 
     * @return
     */
    public static void main(String args) {
        // TODO implement here
        return null;
    }

}